line-length = 135
target-version = "py311"
extend-exclude = ["database/migrations/versions", "firmware-harness"]

[lint]
select = ["E", "F", "W", "I", "B", "UP", "S"]
ignore = ["UP042", "S101", "S311", "S603", "S607", "B008", "S104", "E731", "S108", "B905"]

[lint.per-file-ignores]
"**/tests/**" = ["S", "B", "E501", "E702"]
"tests/**" = ["S", "B", "E501", "E702"]
