"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 18:37:27.569964
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('firmware', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_seen', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('ended_at', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('protocol_version', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('firmware', sa.String(length=200), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_device_id'), 'sessions', ['device_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('stream', sa.String(length=16), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=320), nullable=True),
    sa.Column('acknowledged_at', sa.Float(), nullable=True),
    sa.Column('ack_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_device_id'), 'events', ['device_id'], unique=False)
    op.create_index(op.f('ix_events_t'), 'events', ['t'], unique=False)
    op.create_table('sample_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('stream', sa.String(length=16), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_session_stream_t', 'sample_chunks', ['session_id', 'stream', 't_start'], unique=False)
    op.create_table('vitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('hr_ecg', sa.Float(), nullable=True),
    sa.Column('hr_ppg', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('rr_ms', sa.Float(), nullable=True),
    sa.Column('rr_irregularity', sa.Float(), nullable=True),
    sa.Column('ecg_quality', sa.String(length=12), nullable=True),
    sa.Column('ppg_quality', sa.String(length=12), nullable=True),
    sa.Column('perfusion_index', sa.Float(), nullable=True),
    sa.Column('motion_g', sa.Float(), nullable=True),
    sa.Column('activity', sa.String(length=12), nullable=True),
    sa.Column('roll_deg', sa.Float(), nullable=True),
    sa.Column('pitch_deg', sa.Float(), nullable=True),
    sa.Column('imu_temp_c', sa.Float(), nullable=True),
    sa.Column('battery_soc', sa.Float(), nullable=True),
    sa.Column('skin_temp_c', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vitals_session_t', 'vitals', ['session_id', 't'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vitals_session_t', table_name='vitals')
    op.drop_table('vitals')
    op.drop_index('ix_chunks_session_stream_t', table_name='sample_chunks')
    op.drop_table('sample_chunks')
    op.drop_index(op.f('ix_events_t'), table_name='events')
    op.drop_index(op.f('ix_events_device_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_sessions_device_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
